"""Curated, practical expansions for the core-concepts table in each lesson."""
# Each item: concept, intuition/example, TPM takeaway, metric or formula.
CARDS={
"Computer & TPM basics":[("CPU vs accelerator","CPU orchestrates a request; GPU performs many tensor operations.","Ask which stage is device-bound.","Device busy %; stage latency ms"),("Memory vs storage","Model weights need RAM/VRAM to run; disk holds them between runs.","Confirm capacity and load time.","Peak GB; load seconds"),("API and contract","A client sends prompt plus generation options to an endpoint.","Pin request schema and version.","p95 end-to-end ms; error %"),("Dependency and owner","Driver update is owned by platform team before model qualification.","Track owner, due date and unblock test.","Days blocked"),("Acceptance criterion","A demo passes named prompts at agreed p95 and quality.","Define before execution.","Pass count / total")],
"AI, ML & deep learning":[("AI → ML → DL","A rules engine is AI; learned classifier is ML; LLM is DL.","Choose appropriate evaluation.","Task pass %"),("Training vs inference","Training changes weights; serving a prompt does not.","Do not confuse compute budgets.","Time-to-quality vs tokens/s"),("Supervised learning","Labeled examples teach a spam classifier.","Check label quality and leakage.","Precision/recall"),("Generative model","LLM produces a support reply token by token.","Evaluate factuality and usefulness.","Grounded answer %"),("Tokenizer and context","A 100-word request becomes model-specific tokens.","Pin tokenizer and token counts.","Input tokens/request")],
"System stack & accelerators":[("Driver/runtime","A supported driver exposes the Intel GPU to a framework.","Pin exact compatibility.","Version matrix pass/fail"),("Host and device","CPU tokenization can bottleneck a fast accelerator.","Measure stage timings.","Host vs device ms"),("VRAM and KV cache","Long concurrent chats reserve more attention state.","Test realistic concurrency.","Peak VRAM GB"),("Bandwidth vs capacity","A model may fit yet decode slowly due to data movement.","Test both fit and speed.","GB/s; tokens/s"),("Container image","Same image digest helps reproduce the release.","Record digest and device dependencies.","Reproduction success %")],
"Data & model quality":[("Train/validation/test","Tune on validation; reserve test for final evidence.","Prevent data leakage.","Held-out score"),("Golden set","Include normal, long and adversarial customer prompts.","Make launch criteria explicit.","Pass % by slice"),("Precision","Among flagged items, how many are right?","Use for costly false alarms.","TP/(TP+FP)"),("Recall","Among actual issues, how many were caught?","Use for costly misses.","TP/(TP+FN)"),("Regression gate","New runtime must preserve agreed quality.","Gate performance wins on quality.","Failure count by severity")],
"Training & tuning":[("Epoch/step/batch","One epoch scans data; each step updates weights from a batch.","Estimate duration and memory.","Steps ≈ ceil(N/global batch)"),("Gradient and optimizer","Gradient indicates how weights should change.","Watch instability and reproducibility.","Loss vs step"),("Global batch","Microbatch × accumulation × data-parallel replicas.","Compare effective batch fairly.","Examples/update"),("LoRA adapter","Small trainable layers adapt a frozen base model.","Pin base and adapter versions.","Trainable parameters %"),("Checkpoint","Saved state lets a failed run resume.","Test recovery, not just save.","Restore time min")],
"LLM inference":[("Prefill","A long customer document is processed before first output.","Track prompt-length slices.","TTFT ms"),("Decode","Generated tokens arrive sequentially.","Track output-length slices.","ITL or TPOT ms"),("Queueing","Concurrent arrivals wait for capacity.","Watch tails under load.","p95 queue ms"),("KV cache","Earlier attention state consumes memory.","Plan context × concurrency.","VRAM GB"),("Goodput","Only responses meeting latency/quality SLO count.","Avoid celebrating raw throughput alone.","SLO-compliant tokens/s")],
"Intel platforms & porting":[("Exact SKU","B-series variants can differ in memory and behavior.","Never infer cross-SKU parity.","Pass/fail per SKU"),("Driver and framework","Model portability depends on full supported stack.","Pin versions in bug reports.","Qualification matrix"),("Precision","FP16, BF16 and quantization change fit and outputs.","Agree quality tolerance.","Bytes/parameter; quality delta"),("Operator coverage","Unsupported operation can force fallback or failure.","Identify first failing op.","Unsupported op count"),("Functional parity","Golden outputs pass before benchmark comparison.","Gate performance phase.","Cases passed / total")],
"Benchmark & optimization":[("Warmup","First runs may compile or load caches.","Report cold and warm separately.","Cold-start s"),("Workload shape","Prompt and output length shift bottlenecks.","Publish distributions.","p50/p95 token lengths"),("Concurrency curve","More requests improve use until latency rises.","Find SLO-compliant operating point.","p95 vs requests/s"),("Matched quality","Faster precision can change answers.","Test output quality first.","Quality delta %"),("Repeatability","Single best run hides variation.","Run multiple trials.","Median and range")],
"Serving & Kubernetes":[("Readiness probe","Only route traffic after model can serve.","Test real model readiness.","Ready replicas"),("Startup probe","Allow long model initialization before liveness.","Prevent restart loops.","Startup seconds"),("Liveness probe","Restart a wedged process; avoid false restarts.","Set correct failure conditions.","Restart count"),("HPA metric","CPU-only scaling may miss GPU queue pressure.","Choose workload metrics.","Queue depth; p95"),("Rollback","Restore last qualified image and model.","Practice reversal.","Rollback minutes")],
"Observability & incidents":[("SLI/SLO","Latency SLI measured against a target over a window.","Define numerator and denominator.","p95 < target; availability %"),("Logs/metrics/traces","Events, trends and per-request path complement each other.","Link the same request ID.","Trace coverage %"),("Blast radius","Know affected tenants and requests.","Prioritize mitigation.","Impacted request count"),("Error budget","Tolerance for failures over a defined window.","Escalate based on burn.","Remaining budget %"),("Postmortem","Timeline and prevention items turn incidents into learning.","Assign owners/dates.","Action closure %")],
"RAG & agents":[("Embedding/retrieval","Search finds relevant runbook chunks.","Measure retrieval before answer quality.","Recall@k"),("Grounding","Answer points to retrieved evidence.","Reduce unsupported claims.","Grounded answer %"),("Tool permission","Agent can read wiki but may not modify tickets by default.","Least privilege and approvals.","Unauthorized actions = 0"),("Idempotency/retry","A repeated tool call should not create duplicate tickets.","Design safe retries.","Duplicate rate %"),("End-to-end trace","Follow retrieval, model and tool stages.","Isolate latency and errors.","p95 per stage ms")],
"Customer engineering & career":[("POC exit gate","Customer accepts model accuracy, p95 and cost envelope.","Agree at kickoff.","Criteria met / total"),("RAID log","Risks, assumptions, issues and dependencies stay visible.","Track owner and decision date.","Aged blockers"),("Gap classification","Bug vs unsupported feature vs environment issue.","Route to right owner.","Time to resolution"),("Executive narrative","Goal → evidence → trade-off → decision → next owner.","Make decisions easy.","Decision latency days"),("Career story","Your technical judgement and influence produce an outcome.","Quantify contribution honestly.","Before/after result")],
}

CORE_TABLES={
"AI/ML map":[
("Rule-based AI","Explicit logic","Routing known alerts","Rule coverage","Google ML Crash Course"),
("Classical ML","Fit patterns from data","Ticket classification","Precision/recall","Google ML Crash Course"),
("Deep learning","Multilayer neural networks","Vision or speech model","Held-out quality","PyTorch basics"),
("Generative AI","Produce text, code or images","Support reply draft","Task/grounding pass","Hugging Face LLM course"),
("Agentic workflow","Model selects tools with state","Retrieve then draft ticket","Tool success/permission","Hugging Face LLM course")],
"Lifecycle & ownership":[
("Data","Collect and clean","Leakage, permissions","Coverage, label quality","Google ML Crash Course"),
("Train","Adjust weights","Reproducibility, compute","Time-to-quality","PyTorch basics"),
("Evaluate","Test held-out cases","Acceptance, slices","Precision/recall, pass %","Google ML Crash Course"),
("Serve","Respond to requests","Availability, latency","TTFT, ITL, p95","vLLM docs"),
("Operate","Monitor and improve","SLO, incident, rollback","Error %, goodput","Kubernetes docs")],
"Inference KPI decoder":[
("TTFT","Prompt to first token","Prefill + queue","Milliseconds","vLLM docs"),
("ITL/TPOT","Spacing per later token","Decode","Milliseconds/token","vLLM docs"),
("Throughput","Completed work per time","Capacity","Output tokens/s","MLPerf inference"),
("Goodput","Work inside agreed SLO","Useful capacity","SLO-compliant tokens/s","MLPerf inference"),
("p95 latency","95% of requests at or below","Tail experience","Milliseconds","MLPerf inference")],
"Intel qualification gates":[
("Functional","Model loads and correct outputs","Golden set; pinned stack","Pass %","Intel Arc Pro"),
("Portability","Supported operators and precision","Exact SKU/driver/runtime","Support matrix","OpenVINO GPU"),
("Performance","Fair latency-throughput result","Matched workload/quality","p95; tokens/s","MLPerf inference"),
("Production","Operationally owned release","SLO, rollback, alerts","Availability, MTTR","Kubernetes docs")],
}
LEARNING={
"Google ML Crash Course":"https://developers.google.com/machine-learning/crash-course/classification/accuracy-precision-recall",
"PyTorch basics":"https://docs.pytorch.org/tutorials/beginner/basics/intro",
"Hugging Face LLM course":"https://huggingface.co/learn/llm-course/chapter2/7",
"vLLM docs":"https://docs.vllm.ai/en/latest/",
"Kubernetes docs":"https://kubernetes.io/docs/concepts/workloads/pods/probes/",
"MLPerf inference":"https://docs.mlcommons.org/inference/submission/",
}
