"""Curated AI/ML TPM curriculum; links point to official project documentation."""
REF={
"Intel Arc Pro":"https://www.intel.com/content/dam/www/central-libraries/us/en/documents/2026-03/intel-arc-pro-b-series-graphics-quick-reference-guide-v1-0.pdf",
"Intel Gaudi":"https://www.intel.com/content/www/us/en/products/details/processors/ai-accelerators/gaudi.html",
"Intel Gaudi performance":"https://www.intel.com/content/www/us/en/developer/platform/gaudi/model-performance.html",
"OpenVINO GPU":"https://docs.openvino.ai/2025/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.html",
"PyTorch inference":"https://docs.pytorch.org/docs/stable/generated/torch.autograd.grad_mode.inference_mode.html",
"vLLM prefix cache":"https://docs.vllm.ai/en/latest/features/automatic_prefix_caching.html",
"vLLM disaggregation":"https://docs.vllm.ai/en/latest/features/disagg_prefill/",
"Kubernetes HPA":"https://kubernetes.io/docs/concepts/workloads/autoscaling/horizontal-pod-autoscale/",
"Kubernetes probes":"https://kubernetes.io/docs/concepts/workloads/pods/probes/",
"MLPerf inference":"https://mlcommons.org/benchmarks/inference/",
"MLPerf scenarios":"https://docs.mlcommons.org/inference/submission/",
}
# Title, level, concepts, KPI, formula, customer example, Q/A pairs, references.
ROWS=[
("Computer & TPM basics","Basic",["CPU/RAM/storage: compute, working memory, persistent data","OS/process/container: platform, running program, packaged environment","API/latency/throughput: interface, time per request, work per second"],"Milestone exit criteria; lead time","Lead time = completion date − request date","Turn a customer demo request into named model, owner, hardware, acceptance test and date.",[("What is a measurable exit criterion?","A reproducible outcome with a metric and threshold, such as correct outputs and agreed p95 latency."),("What does a technical TPM own?","Dependencies, decisions, delivery evidence and cross-team alignment.")],["Intel Arc Pro"]),
("AI, ML & deep learning","Basic",["AI is broad; ML learns from data; deep learning uses neural networks","Training updates weights; inference uses weights","Model, tokenizer and dataset have distinct versions"],"Task quality and dataset coverage","Accuracy = correct predictions / examples, when suitable","A support chatbot generates text using an existing model and retrieved context.",[("Does an inference prompt train weights?","Normally no. Training is a separate operation."),("Why pin the tokenizer?","It changes token counts and sometimes compatibility or output.")],["PyTorch inference"]),
("System stack & accelerators","Basic",["Driver/runtime connect frameworks to hardware","VRAM fits weights, KV cache and overhead","Bandwidth and compute affect speed; capacity affects fit"],"Version matrix; memory fit","Usable memory ≈ device memory − weights − KV cache − overhead","A model runs on CPU but fails on Intel GPU: isolate driver, runtime, operator and precision.",[("Why record stack versions?","To reproduce a result and narrow regressions."),("Does fitting in VRAM guarantee performance?","No. Bandwidth, compute, batching and software matter.")],["Intel Arc Pro","OpenVINO GPU"]),
("Data & model quality","Intermediate",["Golden set is representative accepted cases","Precision measures correctness of predicted positives","Recall measures coverage of actual positives"],"Pass rate and failure slices","Precision = TP/(TP+FP); Recall = TP/(TP+FN)","Run a fixed set of customer prompts across languages and long-context cases.",[("Is exact-match text enough for LLM quality?","Often no. Use rubrics and task-specific checks."),("What must be pinned in A/B tests?","Model, tokenizer, prompts, settings, software, precision and scope.")],["MLPerf inference"]),
("Training & tuning","Intermediate",["Epoch is a data pass; batch is examples per update","Loss and gradients drive optimizer updates","Fine-tuning changes behavior; LoRA trains adapters"],"Held-out quality; step time","Steps/epoch ≈ ceil(examples / global batch)","Fine-tune a classifier with a held-out set and checkpoint plan.",[("Does low training loss prove quality?","No. Check held-out data and overfitting."),("Why checkpoints?","To recover and reproduce training progress.")],["Intel Gaudi"]),
("LLM inference","Intermediate",["Prefill processes prompt; decode generates tokens","TTFT is initial wait; ITL is spacing between later tokens","KV cache grows with context and concurrent requests"],"p95 TTFT, p95 ITL, output tokens/s","Response time ≈ TTFT + (output tokens−1) × ITL","Long prompt has slow TTFT: examine prefill and prefix cache.",[("Why p95?","Tail latency reveals slow user experiences."),("What competes for VRAM as concurrency rises?","KV cache and runtime allocations.")],["vLLM prefix cache","vLLM disaggregation"]),
("Intel platforms & porting","Intermediate",["Arc Pro B-series targets discrete workstation GPU use cases","Gaudi has its own accelerator and software stack","OpenVINO supplies inference device plugins"],"Functional parity; supported precision","Weights GB ≈ parameters in billions × bytes/parameter (decimal)","Port a 7B model: verify exact SKU, driver, precision, tokenizer and outputs.",[("Can B70 results be assumed for B60?","No. Validate the exact SKU, model and stack."),("Is peak TOPS enough?","No. Test quality, latency, throughput, cost and operations.")],["Intel Arc Pro","Intel Gaudi","OpenVINO GPU"]),
("Benchmark & optimization","Advanced",["Warmup stabilizes compilation and caches","Concurrency and batching trade utilization against latency","Quantization and prefix cache need quality guardrails"],"p95 latency, tokens/s, quality, cost","Throughput = output tokens / measured seconds","Compare two setups at matched prompt lengths, outputs, precision and concurrency.",[("Why report input/output lengths?","They shift the prefill/decode balance."),("When is optimization acceptable?","Repeated improvement without breaking quality and error guardrails.")],["MLPerf inference","vLLM prefix cache","Intel Gaudi performance"]),
("Serving & Kubernetes","Advanced",["Image packages code; Deployment manages replicas; Service routes","Readiness gates traffic; liveness restarts unhealthy instances","HPA scales replicas using configured metrics"],"Availability, p95, errors, queue","Error rate = failed requests / eligible requests","A traffic spike raises p95: inspect queue, HPA, cold starts and memory.",[("Will more replicas always fix latency?","No. Shared bottlenecks may remain."),("What evidence supports rollout?","Version, test, SLO, dashboard, rollback trigger and owner.")],["Kubernetes HPA"]),
("Observability & incidents","Advanced",["SLI measures behavior; SLO sets its target","Metrics show trends; traces follow requests; logs explain events","Mitigate impact before completing root-cause analysis"],"Error budget, p95, impacted users, MTTR","Availability = successful eligible requests / eligible requests","Runtime update doubles TTFT: assess blast radius and roll back if a guardrail is breached.",[("First incident question?","Who is affected, how badly, and what restores service safely?"),("Why baseline?","It distinguishes regression from workload differences.")],["Kubernetes HPA"]),
("RAG & agents","Advanced",["RAG retrieves external context without weight updates","An agent plans tool calls and carries state","Grounding, permissions and approval protect external actions"],"Retrieval relevance, grounded answers, tool errors","End-to-end latency ≈ retrieval + model + tools + orchestration","Assistant retrieves a runbook and proposes a ticket, with approval before sending.",[("Does RAG retrain the model?","No. Retrieved content is supplied during inference."),("When confirm?","Before consequential external actions.")],["vLLM prefix cache"]),
("Customer engineering & career","Advanced",["POC proves feasibility; pilot tests limited use; production needs SLO","RAID tracks risks, assumptions, issues and dependencies","Executive update states evidence, decision, risk, owner and date"],"Time to first run; acceptance; adoption","Cost/1M output tokens = hourly serving cost / output tokens/hour × 1,000,000","Intel customer POC: baseline, qualify, benchmark, resolve gaps and get sign-off.",[("What is a senior TPM update?","Outcome, evidence, top risk, decision needed, owner and date."),("What makes an interview story credible?","Scope, your decisions and influence, quantified result and learning.")],["Intel Arc Pro","Intel Gaudi performance"]),
]
LESSONS=[{"title":a,"level":b,"terms":c,"metric":d,"formula":e,"example":f,"quiz":g,"refs":h} for a,b,c,d,e,f,g,h in ROWS]
for lesson in LESSONS:
    if lesson["title"]=="Serving & Kubernetes": lesson["refs"].append("Kubernetes probes")
    if lesson["title"]=="Benchmark & optimization": lesson["refs"].append("MLPerf scenarios")
